name: Create Jira Issue

on:
  issues:
    types: [opened]

jobs:
  create_jira_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        uses: atlassian/gajira-create@v3
        with:
          project: "ETR"  # Jira 프로젝트 키
          issuetype: "Task"
          summary: "${{ github.event.issue.title }}"
          description: "${{ github.event.issue.body }}"
        env:
          JIRA_BASE_URL: "https://yourcompany.atlassian.net"
          JIRA_USER_EMAIL: "${{ secrets.JIRA_EMAIL }}"
          JIRA_API_TOKEN: "${{ secrets.JIRA_API_TOKEN }}"
