name: Create Jira issue

on:
  issues:
    types:
      - opened

jobs:
  create-issue:
    name: Create Jira issue
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main code
        uses: actions/checkout@v4

      - name: Login to Jira
        id: jira-login
        uses: atlassian/gajira-login@v3
        with:
          site: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}

      - name: Verify Jira Login
        run: |
          if [ ! -f "/home/runner/jira/config.yml" ]; then
            echo "❌ Jira 로그인 실패! config.yml 파일이 없음."
            exit 1
          else
            echo "✅ Jira 로그인 성공! config.yml 파일 확인됨."
          fi

      - name: Convert markdown to Jira Syntax
        uses: peter-evans/jira2md@v1
        id: md2jira
        with:
          input-text: |
            ### Github Issue Link
            - ${{ github.event.issue.html_url }}

            ${{ github.event.issue.body }}
          mode: md2jira

      - name: Create Jira Issue
        id: create
        uses: atlassian/gajira-create@v3
        with:
          site: ${{ secrets.JIRA_BASE_URL }}
          email: ${{ secrets.JIRA_USER_EMAIL }}
          apiToken: ${{ secrets.JIRA_API_TOKEN }}
          project: "ETR"
          issuetype: "작업"  # ✅ 한글로 변경 (Task → 작업)
          summary: "[GitHub] ${{ github.event.issue.title }}"
          description: "${{ steps.md2jira.outputs.output-text }}"

      - name: Log Created Issue
        run: echo "✅ Jira Issue 생성 완료: ${{ steps.create.outputs.issue }}"
